# Base runtime image
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

# Build stage
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src

# Copy the project file (because it's in the same folder as the Dockerfile)
COPY ["CICD_APP.csproj", "./"]

# Restore dependencies
RUN dotnet restore "CICD_APP.csproj"

# Copy all source files
COPY . .

# Build
RUN dotnet build "CICD_APP.csproj" -c $BUILD_CONFIGURATION -o /app/build

# Publish stage
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "CICD_APP.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

# Final container image
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "CICD_APP.dll"]
