name: Check JFrog Token

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Extract token ID
        id: extract
        run: |
          TOKEN="${{ secrets.JFROG_PASSWORD  }}"
          
          # Decode base64
          DECODED=$(echo "$TOKEN" | base64 --decode)
          
          # Format: reftkn:01:<expiry_epoch_seconds>:<random>
          EXPIRY_EPOCH=$(echo "$DECODED" | cut -d ':' -f3)
          
          NOW=$(date +%s)
          DIFF=$((EXPIRY_EPOCH - NOW))
          DAYS_LEFT=$((DIFF / 86400))
          
          echo "days_left=$DAYS_LEFT" >> $GITHUB_OUTPUT
          echo "Token expires in $DAYS_LEFT days"
